version: '3.8' # Versão do Docker Compose

services: # Serviços Necessários
  postgres: # Configura uma Imagem do POSTGRESQL
    image: postgres:15-alpine
    container_name: lynq-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lynq-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis: # Configura a Imagem do REDISj
    image: redis:7-alpine
    container_name: lynq-redis
    ports:
      - "6379:6479"
    restart: unless-stopped
    volumes: 
      - redis_data:/data
  
volumes:
  postgres_data:
  redis_data:
